if (AURORA_TARGET_RVL)
	add_library(aurora_nand STATIC lib/revolution/nand/nand.cpp)
	add_library(aurora::nand ALIAS aurora_nand)
	set_target_properties(aurora_nand PROPERTIES FOLDER "aurora")
	target_include_directories(aurora_nand PUBLIC include)
	target_link_libraries(aurora_nand PRIVATE aurora::core)
endif ()
